export const CHALLENGE_TEMPLATES = [
  {
    id: "winter-arc",
    name: "Winter Arc",
    days: 90,
    strict: false,
    accent: "winter",
    desc: "Собрать дисциплину, форму и режим за холодный сезон.",
    trend: [10, 11, 12, 1],
    rules: ["Тренировка каждый день", "Сон по режиму", "10 минут планирования", "Без лишнего сахара"],
  },
  {
    id: "75-hard",
    name: "75 Hard",
    days: 75,
    strict: true,
    accent: "hard",
    desc: "Жёсткий режим без права на пропуск.",
    trend: [1, 2, 9],
    rules: ["Тренировка каждый день", "Питание по плану", "Вода каждый день", "Чтение 10 страниц"],
  },
  {
    id: "plank-30",
    name: "30 дней планки",
    days: 30,
    strict: false,
    accent: "strength",
    desc: "Короткая ежедневная работа на корпус.",
    trend: [3, 4, 5],
    rules: ["Планка каждый день", "Записывай время", "Не гонись за рекордом в первые дни"],
  },
  {
    id: "no-sugar-month",
    name: "Месяц без сахара",
    days: 30,
    strict: false,
    accent: "fresh",
    desc: "Снизить сладкое и стабилизировать аппетит.",
    trend: [1, 5, 6],
    rules: ["Без сладких напитков", "Без десертов", "Фрукты можно", "Отмечай день вечером"],
  },
  {
    id: "steps-10000",
    name: "10 000 шагов",
    days: 30,
    strict: false,
    accent: "move",
    desc: "Больше ходьбы без сложной подготовки.",
    trend: [4, 5, 6, 7, 8],
    rules: ["10 000 шагов в день", "Прогулка считается", "Не добивай шаги через боль"],
  },
  {
    id: "cold-shower",
    name: "Холодный душ",
    days: 30,
    strict: false,
    accent: "winter",
    desc: "Небольшая ежедневная тренировка воли.",
    trend: [6, 7, 8],
    rules: ["Холодный душ каждый день", "Начинай с короткого времени", "Не делай при плохом самочувствии"],
  },
  {
    id: "no-social-14",
    name: "14 дней без соцсетей",
    days: 14,
    strict: false,
    accent: "focus",
    desc: "Освободить внимание и вернуть контроль над экраном.",
    trend: [9, 10, 1],
    rules: ["Без ленты соцсетей", "Мессенджеры по делу", "Замени скролл прогулкой или чтением"],
  },
  {
    id: "meditation-21",
    name: "Медитация 21 день",
    days: 21,
    strict: false,
    accent: "calm",
    desc: "Сделать паузу привычкой.",
    trend: [1, 2, 3, 12],
    rules: ["Медитация каждый день", "5 минут достаточно", "Отмечай сразу после практики"],
  },
];

export function challengeTemplateById(id) {
  return CHALLENGE_TEMPLATES.find((template) => template.id === id) || null;
}
